<?php

namespace App;

use App\Notifications\NewPromotion;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class Promotion extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'isActive', 'discount', 'code', 'name'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function($model){
            if (!$model->isActive) return;
            $users = User::where('promotion_opt_in', '=', 1)->get();
            foreach ($users as $user) {
                $user->notify(new NewPromotion($model->code, $model->discount, $model->name));
            }
        });

        self::updated(function($model) {
            if(!$model->isActive) return;
            $users = User::where('promotion_opt_in', '=', 1)->get();
            foreach ($users as $user) {
                $user->notify(new NewPromotion($model->code, $model->discount, $model->name));
            }
        });
    }

    public function pricing() {
        return $this->hasMany('App\Pricing');
    }
}
