<?php

namespace App;

use App\Notifications\newPromotion;
use App\Notifications\newTicket;
use Illuminate\Database\Eloquent\Model;
use App\User;
use Illuminate\Support\Facades\Auth;

class Ticket extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'seat_id', 'showroom_id', 'user', 'showing_id', 'ticket_type_id', 'booking_id'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::created(function($model){
            $user = Auth::user();
            $showing = Showing::where('id', $model->showing_id)->first();
            $showroom = Showroom::where('id', $model->showroom_id)->first();
            $ticket_type = TicketType::where('id', $model->ticket_type_id)->first();
            $movie = Movie::where('id', $showing->movie_id)->first();
            $booking = Booking::where('id', $model->booking_id)->first();
            $seat = Seat::where('id', $model->seat_id)->first();
            $user->notify(new newTicket($showing->dateTime, $showroom->id, $movie->title, $seat->number, $ticket_type->Name, $booking->bookingNumber));
        });
    }



    public function user() {
        return $this->belongsTo('App\User');
    }

    public function showroom() {
        return $this->belongsTo('App\Showroom');
    }

    public function showing() {
        return $this->belongsTo('App\Showing');
    }

    public function TicketType() {
        return $this->belongsTo('App\TicketType');
    }

    public function Seat() {
        return $this->belongsTo('App\Seat');
    }

    public function Booking() {
        return $this->belongsTo('App\Booking');
    }
}
